remote_theme: pages-theme/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

title: Elvis AEs website.
description: In 2024, why not?

show_downloads: [true](nothing.com/)
#  google_analytics: [Your Google Analytics tracking ID]
