# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-0HREPR42SV'

menu:
- {name: 'Resume', url: 'resume'}
- {name: 'CV',       url: 'CV'}
#- {name: 'Documentation',      url: 'documentation'}
#- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}
- {name: 'Interests',       url: 'interests'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'x-twitter', link:    'https://x.com/ElvisAE1'}
- {icon: 'facebook', link:   'https://www.facebook.com/elvis90'}
- {icon: 'instagram', link:  'https://www.instagram.com/__otherelvis__/'}
- {icon: 'envelope', link:   'mailto:elvis.ae@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
- {icon: 'linkedin-in', link: 'https://www.linkedin.com/in/elviseugene'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
